<?php

use function Livewire\Volt\{title};

title('Formwerk - Übersicht');

?>

<x-intranet-app-formwerk::formwerk-layout heading="Formwerk App" subheading="Übersicht">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-formwerk::formwerk-layout>